{
 "title": "WebProject",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "users-api",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_server_active_requests{job=\"users-api\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "http_server_request_duration_seconds_count{job=\"users-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "bookings-appi",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "http_server_request_duration_seconds_count{job=\"bookings-api\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "http_server_active_requests{job=\"bookings-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "event-api",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "http_server_active_requests{job=\"events-api\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "http_server_request_duration_seconds_count{job=\"events-api\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  }
 ]
}